### ISSUE TITLE
Warning in dev / test

### ISSUE THREAD

**Issue by lewispb** [errm/promenade#1]
`WARN -- : Please set prometheus_multiproc_dir to persistent directory path. Temporarily writing mmap files to /var/folders/j2/g1g_491d3td9pxt7wx70brdh0000gn/T/prometheus-mmap20181128-86033-dx4yuq`

Would be nice to not see this in dev and test :)

**Comment by davidstosik** [comment]
Should we move the `promenade` [gem](https://github.com/cookpad/global-web/blob/master/Gemfile#L69) to a staging/production only group?

**Comment by errm** [comment]
You could do that, but only if you don't use it's DSL directly in code that you are using in tests ...

Also yet you might prefer for your tests to exercise it's code paths 🤷‍♂️ depending on how much you trust it to be stable!

**Comment by davidstosik** [comment]
>  you might prefer for your tests to exercise it's code paths

That's a very good point. I thought promenade was mostly disabled in dev/test because it had no environment set up.

**Comment by errm** [comment]
Version `0.1.10` should include the fix for this issue....
